// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkqgqBwDLg4Ir9TOeg47oti3Rrna2QvfU',
    appId: '1:722179987032:web:ac31776ea891d484711c2d',
    messagingSenderId: '722179987032',
    projectId: 'calender-imu',
    authDomain: 'calender-imu.firebaseapp.com',
    storageBucket: 'calender-imu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw-fZO8n5kb96Q08yxT_GfoUEYnOz7IoU',
    appId: '1:722179987032:android:3b0b356363982450711c2d',
    messagingSenderId: '722179987032',
    projectId: 'calender-imu',
    storageBucket: 'calender-imu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcoT52UvMd3_HcVc6iS_TjHqLVaNK6kNA',
    appId: '1:722179987032:ios:c804cf7d70bd3f59711c2d',
    messagingSenderId: '722179987032',
    projectId: 'calender-imu',
    storageBucket: 'calender-imu.firebasestorage.app',
    iosBundleId: 'com.example.calenderimu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcoT52UvMd3_HcVc6iS_TjHqLVaNK6kNA',
    appId: '1:722179987032:ios:c804cf7d70bd3f59711c2d',
    messagingSenderId: '722179987032',
    projectId: 'calender-imu',
    storageBucket: 'calender-imu.firebasestorage.app',
    iosBundleId: 'com.example.calenderimu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkqgqBwDLg4Ir9TOeg47oti3Rrna2QvfU',
    appId: '1:722179987032:web:890aaf9cf25c3a7c711c2d',
    messagingSenderId: '722179987032',
    projectId: 'calender-imu',
    authDomain: 'calender-imu.firebaseapp.com',
    storageBucket: 'calender-imu.firebasestorage.app',
  );

}